/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment1.Users;

import assignment1.MainWindows.AppManager;
import assignment1.MainWindows.MainFrame;
import assignment1.QuestionsGUI.*;
import javax.swing.JFrame;

/**
 *
 * @author Ahmed
 */
public class Professor extends javax.swing.JPanel
{

    /**
     * Creates new form prof
     */
    public Professor()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        TrueFalse = new javax.swing.JButton();
        ShortAnswer = new javax.swing.JButton();
        LongAnswer = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        TrueFalse.setText("True or false");
        TrueFalse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TrueFalseActionPerformed(evt);
            }
        });

        ShortAnswer.setText("Short Answer");
        ShortAnswer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ShortAnswerActionPerformed(evt);
            }
        });

        LongAnswer.setText("Long Answer");
        LongAnswer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LongAnswerActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TrueFalse)
                        .addGap(18, 18, 18)
                        .addComponent(ShortAnswer)
                        .addGap(18, 18, 18)
                        .addComponent(LongAnswer))
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrueFalse)
                    .addComponent(ShortAnswer)
                    .addComponent(LongAnswer))
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TrueFalseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TrueFalseActionPerformed
    {//GEN-HEADEREND:event_TrueFalseActionPerformed
        // Move to the new T / F window
        JFrame trueOrFalseWindow = new TrueOrFalse();
        trueOrFalseWindow.setVisible(true);
    }//GEN-LAST:event_TrueFalseActionPerformed

    private void ShortAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ShortAnswerActionPerformed
    {//GEN-HEADEREND:event_ShortAnswerActionPerformed
        // Load a short answer question window
        JFrame shortAnswerWindow = new ShortAnswer();
        shortAnswerWindow.setVisible(true);
    }//GEN-LAST:event_ShortAnswerActionPerformed

    private void LongAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LongAnswerActionPerformed
    {//GEN-HEADEREND:event_LongAnswerActionPerformed
        // Load a long answer question window
        JFrame longAnswerWindow = new LongAnswer();
        longAnswerWindow.setVisible(true);
    }//GEN-LAST:event_LongAnswerActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // TODO Save the file then close the application
        AppManager.writeToFile();
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LongAnswer;
    private javax.swing.JButton ShortAnswer;
    private javax.swing.JButton TrueFalse;
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
}
