/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment1.Users;

import assignment1.MainWindows.AppManager;
import assignment1.QuestionsGUI.LongAnswer;
import assignment1.QuestionsGUI.ShortAnswer;
import assignment1.QuestionsGUI.TrueOrFalse;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed
 */
public final class Student extends javax.swing.JPanel
{

    private static int questionCounter ;
    // Empty frame to hold the next question
    public static JFrame nextQuestion;

    public Student()
    {
        initComponents();
        questionCounter = 0;
        
        updateScoreBoard();
        nameLabel.setText("Welcome " + AppManager.studentName + " , take your quiz!");

        // Repaint the Frame
        this.repaint();
        getNextQuestionWindow();
        AppManager.answeredQuestionsCount = 0;
    }

    public static void getNextQuestionWindow()
    {
        questionCounter++;
        String questionType = AppManager.currentQuestion.questionType;

        // Show the JFrame according to the type of the question
        switch (questionType)
        {
            case "LongAnswer":
                nextQuestion = new LongAnswer();
                break;
            case "ShortAnswer":
                nextQuestion = new ShortAnswer();
                break;
            case "TrueFalse":
                nextQuestion = new TrueOrFalse();
                break;
        }
        nextQuestion.setVisible(true);

        // Update the score board
        updateScoreBoard();

    }

    public static void updateScoreBoard()
    {
        markLabel.setText((questionCounter + " / " + AppManager.questionCount + " questions"));
        quizProgBar.setValue((int) (((float) AppManager.answeredQuestionsCount / (float) AppManager.questionCount) * 100.0));
    }

    public static void endQuiz()
    {
        String message;
        if (AppManager.answeredQuestionsCount == AppManager.questionCount)
        {
            message = AppManager.studentName+", You passed :( ";
        }
        else
        {
            message = "You failed " + AppManager.studentName + ",  don't try again";
        }

        JOptionPane.showMessageDialog(null, message);

        // Terminate the program
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        markLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        quizProgBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quiz Status"));

        jLabel1.setText("Questions Attacked");

        markLabel.setText("                                ");

        nameLabel.setText("       ");

        jLabel2.setText("Fail");

        jLabel3.setText("Pass");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(markLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(quizProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(quizProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(markLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel markLabel;
    public static javax.swing.JLabel nameLabel;
    private static javax.swing.JProgressBar quizProgBar;
    // End of variables declaration//GEN-END:variables
}
